// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_mcmc
Rcpp::List run_mcmc(arma::mat& y, arma::mat& X, const std::string& family, unsigned int nIter, unsigned int burnin, unsigned int thin, unsigned int tick, const std::string& gamma_sampler, const std::string& gammaProposal, const std::string& gamma_gibbs, int threads, unsigned int n, int nsamp, int ninit, double convex, int npoint, const Rcpp::List& initList, const Rcpp::List& rangeList, const Rcpp::List& hyperparList);
RcppExport SEXP _brmss_run_mcmc(SEXP ySEXP, SEXP XSEXP, SEXP familySEXP, SEXP nIterSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP tickSEXP, SEXP gamma_samplerSEXP, SEXP gammaProposalSEXP, SEXP gamma_gibbsSEXP, SEXP threadsSEXP, SEXP nSEXP, SEXP nsampSEXP, SEXP ninitSEXP, SEXP convexSEXP, SEXP npointSEXP, SEXP initListSEXP, SEXP rangeListSEXP, SEXP hyperparListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type family(familySEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nIter(nIterSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type tick(tickSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type gamma_sampler(gamma_samplerSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type gammaProposal(gammaProposalSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type gamma_gibbs(gamma_gibbsSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< int >::type ninit(ninitSEXP);
    Rcpp::traits::input_parameter< double >::type convex(convexSEXP);
    Rcpp::traits::input_parameter< int >::type npoint(npointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type initList(initListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rangeList(rangeListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type hyperparList(hyperparListSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc(y, X, family, nIter, burnin, thin, tick, gamma_sampler, gammaProposal, gamma_gibbs, threads, n, nsamp, ninit, convex, npoint, initList, rangeList, hyperparList));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_brmss_run_mcmc", (DL_FUNC) &_brmss_run_mcmc, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_brmss(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
