# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Main function implemented in C++ for the MCMC loop
#'
#' @name run_mcmc
#'
#' @param y response variable. A vector, matrix or dataframe
#' @param X input matrix or dataframe
#' @param L number of response variables
#' @param family a character string representing one of the built-in families
#' @param nIter the number of iterations of the chain
#' @param burnin number of iterations to discard at the start of the chain
#' @param thin thinning MCMC intermediate results to be stored
#' @param tick an integer used for printing the iteration index and some updated
#' parameters every tick-th iteration. Default is 1
#' @param gamma_sampler M-H sampler with "mc" or multi-armed "bandit" proposal for gammas
#' @param gamma_proposal one of 'c("simple", "posterior")'
#' @param threads number of threads used for parallelization. Default is 1
#' @param n number of samples to draw
#' @param nsamp how many samples to draw for generating each sample; only the last draw will be kept
#' @param ninit number of initials as meshgrid values for envelop search
#' @param convex adjustment for convexity (non-negative value, default 1.0)
#' @param npoint maximum number of envelope points
#' @param initList a list of initial values for parameters "kappa", "betas"
#' @param rangeList a list of ranges of initial values for parameters "kappa", "betas"
#' @param hyperparList a list of relevant hyperparameters
#'
run_mcmc <- function(y, X, L, family, nIter, burnin, thin, tick, gamma_sampler, gamma_proposal, threads, n, nsamp, ninit, convex, npoint, initList, rangeList, hyperparList) {
    .Call(`_brmss_run_mcmc`, y, X, L, family, nIter, burnin, thin, tick, gamma_sampler, gamma_proposal, threads, n, nsamp, ninit, convex, npoint, initList, rangeList, hyperparList)
}

